language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t jaumealg77/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jaumealg77/react-test npm test

after_success:
    - docker build -t jaumealg77/multi-client ./client
    - docker build -t jaumealg77/multi-nginx ./nginx
    - docker build -t jaumealg77/multi-server ./server
    - docker build -t jaumealg77/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push jaumealg77/multi-client
    - docker push jaumealg77/multi-nginx
    - docker push jaumealg77/multi-server
    - docker push jaumealg77/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-west-2-947091224738" 
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY     